import pickle
from flask import Flask, request, jsonify

app = Flask(__name__)

# ✅ Load the trained model
model_path = r"C:\Users\asus\OneDrive\Desktop\jupyter\model.pkl"

with open(model_path, "rb") as file:
    model = pickle.load(file)

print("✅ Model loaded successfully!")

@app.route("/recommend", methods=["POST"])
def recommend():
    data = request.get_json()
    user_id = data.get("user_id")

    if not user_id:
        return jsonify({"error": "User ID is required"}), 400

   
    recommended_movies = [
    {"title": "Mad Max: Fury Road", "genre": "Action", "rating": 8.1},
    {"title": "John Wick", "genre": "Action", "rating": 7.4},
    {"title": "The Dark Knight", "genre": "Action", "rating": 9.0},
    {"title": "Gladiator", "genre": "Action", "rating": 8.5},
    {"title": "Die Hard", "genre": "Action", "rating": 8.2},
    {"title": "Avengers: Endgame", "genre": "Action", "rating": 8.4},
    {"title": "Black Panther", "genre": "Action", "rating": 7.3},
    {"title": "Logan", "genre": "Action", "rating": 8.1},
    {"title": "Deadpool", "genre": "Action", "rating": 8.0},
    {"title": "The Bourne Ultimatum", "genre": "Action", "rating": 8.0},
    {"title": "Tenet", "genre": "Action", "rating": 7.4},
    {"title": "The Raid: Redemption", "genre": "Action", "rating": 7.6},
    {"title": "The Equalizer", "genre": "Action", "rating": 7.2},
    {"title": "Dredd", "genre": "Action", "rating": 7.1},
    {"title": "Pacific Rim", "genre": "Action", "rating": 6.9},
    {"title": "Shazam!", "genre": "Action", "rating": 7.0},
    {"title": "Edge of Tomorrow", "genre": "Action", "rating": 7.9},
    {"title": "Bloodsport", "genre": "Action", "rating": 6.8},
    {"title": "The Expendables", "genre": "Action", "rating": 6.5},
    {"title": "Mortal Kombat", "genre": "Action", "rating": 6.1},
    {"title": "The Suicide Squad", "genre": "Action", "rating": 7.2},
    {"title": "The Batman", "genre": "Action", "rating": 8.0},
    {"title": "Captain America: Civil War", "genre": "Action", "rating": 7.8},
    {"title": "Spider-Man: No Way Home", "genre": "Action", "rating": 8.7},
    {"title": "Thor: Ragnarok", "genre": "Action", "rating": 7.9},
    {"title": "Man of Steel", "genre": "Action", "rating": 7.1},
    {"title": "The Fast and the Furious", "genre": "Action", "rating": 6.8},
    {"title": "Atomic Blonde", "genre": "Action", "rating": 6.7},
    {"title": "Léon: The Professional", "genre": "Action", "rating": 8.5},
    {"title": "300", "genre": "Action", "rating": 7.6},
    {"title": "Oldboy", "genre": "Action", "rating": 8.4},
    {"title": "Uncharted", "genre": "Action", "rating": 6.5},
    {"title": "Kingsman: The Secret Service", "genre": "Action", "rating": 7.7},
    {"title": "The Accountant", "genre": "Action", "rating": 7.3},
    {"title": "Rambo: First Blood", "genre": "Action", "rating": 7.7},
    {"title": "Predator", "genre": "Action", "rating": 7.8},
    {"title": "Godzilla vs. Kong", "genre": "Action", "rating": 6.3},
    {"title": "The Maze Runner", "genre": "Action", "rating": 6.8},
    {"title": "The Book of Eli", "genre": "Action", "rating": 6.9},
    {"title": "Rogue One: A Star Wars Story", "genre": "Action", "rating": 7.8},
    {"title": "Solo: A Star Wars Story", "genre": "Action", "rating": 6.9},
    {"title": "The Meg", "genre": "Action", "rating": 5.7},
    {"title": "Skyscraper", "genre": "Action", "rating": 5.9},
    {"title": "Resident Evil: Welcome to Raccoon City", "genre": "Action", "rating": 5.2},
    {"title": "The Great Wall", "genre": "Action", "rating": 5.9},
    {"title": "Alita: Battle Angel", "genre": "Action", "rating": 7.3},
    {"title": "Venom", "genre": "Action", "rating": 6.7},
    {"title": "Black Adam", "genre": "Action", "rating": 6.5},
    {"title": "Titanic", "genre": "Romance", "rating": 7.8},
    {"title": "La La Land", "genre": "Romance", "rating": 8.0},
    {"title": "Pride & Prejudice", "genre": "Romance", "rating": 7.8},
    {"title": "The Notebook", "genre": "Romance", "rating": 7.8},
    {"title": "500 Days of Summer", "genre": "Romance", "rating": 7.7},
    {"title": "A Walk to Remember", "genre": "Romance", "rating": 7.4},
    {"title": "Me Before You", "genre": "Romance", "rating": 7.4},
    {"title": "The Fault in Our Stars", "genre": "Romance", "rating": 7.7},
    {"title": "Pretty Woman", "genre": "Romance", "rating": 7.1},
    {"title": "10 Things I Hate About You", "genre": "Romance", "rating": 7.3},
    {"title": "Notting Hill", "genre": "Romance", "rating": 7.1},
    {"title": "Crazy Rich Asians", "genre": "Romance", "rating": 7.0},
    {"title": "To All the Boys I've Loved Before", "genre": "Romance", "rating": 7.1},
    {"title": "Love Actually", "genre": "Romance", "rating": 7.6},
    {"title": "Before Sunrise", "genre": "Romance", "rating": 8.1},
    {"title": "Before Sunset", "genre": "Romance", "rating": 8.0},
    {"title": "Before Midnight", "genre": "Romance", "rating": 7.9},
    {"title": "About Time", "genre": "Romance", "rating": 7.8},
    {"title": "The Vow", "genre": "Romance", "rating": 6.8},
    {"title": "Safe Haven", "genre": "Romance", "rating": 6.7},
    {"title": "Dear John", "genre": "Romance", "rating": 6.3},
    {"title": "One Day", "genre": "Romance", "rating": 7.0},
    {"title": "The Best of Me", "genre": "Romance", "rating": 6.7},
    {"title": "Letters to Juliet", "genre": "Romance", "rating": 6.5},
    {"title": "Love, Rosie", "genre": "Romance", "rating": 7.1},
    {"title": "The Age of Adaline", "genre": "Romance", "rating": 7.2},
    {"title": "The Longest Ride", "genre": "Romance", "rating": 7.0},
    {"title": "Moulin Rouge!", "genre": "Romance", "rating": 7.6},
    {"title": "Beauty and the Beast", "genre": "Romance", "rating": 7.1},
    {"title": "Romeo + Juliet", "genre": "Romance", "rating": 6.7},
    {"title": "Sleepless in Seattle", "genre": "Romance", "rating": 6.8},
    {"title": "The Holiday", "genre": "Romance", "rating": 6.9},
    {"title": "Bridget Jones's Diary", "genre": "Romance", "rating": 7.1},
    {"title": "Sweet Home Alabama", "genre": "Romance", "rating": 6.2},
    {"title": "While You Were Sleeping", "genre": "Romance", "rating": 6.7},
    {"title": "The Proposal", "genre": "Romance", "rating": 6.7},
    {"title": "Ever After: A Cinderella Story", "genre": "Romance", "rating": 7.0},
    {"title": "Eat Pray Love", "genre": "Romance", "rating": 5.8},
    {"title": "Shakespeare in Love", "genre": "Romance", "rating": 7.1},
    {"title": "The Time Traveler's Wife", "genre": "Romance", "rating": 7.1},
    {"title": "P.S. I Love You", "genre": "Romance", "rating": 7.0},
    {"title": "The Lake House", "genre": "Romance", "rating": 6.8},
    {"title": "Something's Gotta Give", "genre": "Romance", "rating": 6.7},
    {"title": "Hitch", "genre": "Romance", "rating": 6.6},
    {"title": "Enchanted", "genre": "Romance", "rating": 7.1},
    {"title": "My Big Fat Greek Wedding", "genre": "Romance", "rating": 6.6},
    {"title": "How to Lose a Guy in 10 Days", "genre": "Romance", "rating": 6.4},
    {"title": "Interstellar", "genre": "Sci-Fi", "rating": 8.6},
    {"title": "Inception", "genre": "Sci-Fi", "rating": 8.8},
    {"title": "Blade Runner 2049", "genre": "Sci-Fi", "rating": 8.0},
    {"title": "The Matrix", "genre": "Sci-Fi", "rating": 8.7},
    {"title": "The Martian", "genre": "Sci-Fi", "rating": 8.0},
    {"title": "Dune", "genre": "Sci-Fi", "rating": 8.1},
    {"title": "Arrival", "genre": "Sci-Fi", "rating": 7.9},
    {"title": "Star Wars: A New Hope", "genre": "Sci-Fi", "rating": 8.6},
    {"title": "Star Wars: The Empire Strikes Back", "genre": "Sci-Fi", "rating": 8.7},
    {"title": "Star Wars: Return of the Jedi", "genre": "Sci-Fi", "rating": 8.3},
    {"title": "Guardians of the Galaxy", "genre": "Sci-Fi", "rating": 8.0},
    {"title": "E.T. the Extra-Terrestrial", "genre": "Sci-Fi", "rating": 7.8},
    {"title": "RoboCop", "genre": "Sci-Fi", "rating": 7.6},
    {"title": "The Terminator", "genre": "Sci-Fi", "rating": 8.1},
    {"title": "Terminator 2: Judgment Day", "genre": "Sci-Fi", "rating": 8.6},
    {"title": "A Quiet Place", "genre": "Sci-Fi", "rating": 7.6},
    {"title": "Edge of Tomorrow", "genre": "Sci-Fi", "rating": 7.9},
    {"title": "Pacific Rim", "genre": "Sci-Fi", "rating": 6.9},
    {"title": "Godzilla vs. Kong", "genre": "Sci-Fi", "rating": 6.3},
    {"title": "Oblivion", "genre": "Sci-Fi", "rating": 7.0},
    {"title": "Gravity", "genre": "Sci-Fi", "rating": 7.7},
    {"title": "Prometheus", "genre": "Sci-Fi", "rating": 7.0},
    {"title": "Alien", "genre": "Sci-Fi", "rating": 8.5},
    {"title": "Aliens", "genre": "Sci-Fi", "rating": 8.4},
    {"title": "Predator", "genre": "Sci-Fi", "rating": 7.8},
    {"title": "The Fifth Element", "genre": "Sci-Fi", "rating": 7.7},
    {"title": "Snowpiercer", "genre": "Sci-Fi", "rating": 7.1},
    {"title": "I, Robot", "genre": "Sci-Fi", "rating": 7.1},
    {"title": "Tron: Legacy", "genre": "Sci-Fi", "rating": 6.8},
    {"title": "The War of the Worlds", "genre": "Sci-Fi", "rating": 7.1},
    {"title": "Annihilation", "genre": "Sci-Fi", "rating": 6.8},
    {"title": "District 9", "genre": "Sci-Fi", "rating": 7.9},
    {"title": "Looper", "genre": "Sci-Fi", "rating": 7.4},
    {"title": "The Time Machine", "genre": "Sci-Fi", "rating": 7.1},
    {"title": "Event Horizon", "genre": "Sci-Fi", "rating": 6.7},
    {"title": "Serenity", "genre": "Sci-Fi", "rating": 7.8},
    {"title": "Children of Men", "genre": "Sci-Fi", "rating": 7.9},
    {"title": "Minority Report", "genre": "Sci-Fi", "rating": 7.7},
    {"title": "The Day the Earth Stood Still", "genre": "Sci-Fi", "rating": 7.5},
    {"title": "Fantastic Planet", "genre": "Sci-Fi", "rating": 7.7},
    {"title": "2001: A Space Odyssey", "genre": "Sci-Fi", "rating": 8.3},
    {"title": "Contact", "genre": "Sci-Fi", "rating": 7.4},
    {"title": "Gattaca", "genre": "Sci-Fi", "rating": 7.8},
    {"title": "The Andromeda Strain", "genre": "Sci-Fi", "rating": 7.2},
    {"title": "Dark City", "genre": "Sci-Fi", "rating": 7.6},
    {"title": "The Man from Earth", "genre": "Sci-Fi", "rating": 7.9},
    {"title": "The Invisible Man", "genre": "Sci-Fi", "rating": 7.1},
    {"title": "The Hangover", "genre": "Comedy", "rating": 7.7},
    {"title": "Superbad", "genre": "Comedy", "rating": 7.6},
    {"title": "Step Brothers", "genre": "Comedy", "rating": 6.9},
    {"title": "Dumb and Dumber", "genre": "Comedy", "rating": 7.3},
    {"title": "Anchorman", "genre": "Comedy", "rating": 7.2},
    {"title": "Zombieland", "genre": "Comedy", "rating": 7.6},
    {"title": "Ghostbusters", "genre": "Comedy", "rating": 7.8},
    {"title": "Jumanji: Welcome to the Jungle", "genre": "Comedy", "rating": 7.0},
    {"title": "The Grand Budapest Hotel", "genre": "Comedy", "rating": 8.1},
    {"title": "The Nice Guys", "genre": "Comedy", "rating": 7.4},
    {"title": "Tropic Thunder", "genre": "Comedy", "rating": 7.0},
    {"title": "Game Night", "genre": "Comedy", "rating": 6.9},
    {"title": "We're the Millers", "genre": "Comedy", "rating": 7.0},
    {"title": "Horrible Bosses", "genre": "Comedy", "rating": 6.8},
    {"title": "21 Jump Street", "genre": "Comedy", "rating": 7.2},
    {"title": "22 Jump Street", "genre": "Comedy", "rating": 7.0},
    {"title": "Shaun of the Dead", "genre": "Comedy", "rating": 7.9},
    {"title": "Hot Fuzz", "genre": "Comedy", "rating": 7.8},
    {"title": "The World's End", "genre": "Comedy", "rating": 6.9},
    {"title": "Knocked Up", "genre": "Comedy", "rating": 6.9},
    {"title": "Forgetting Sarah Marshall", "genre": "Comedy", "rating": 7.1},
    {"title": "Bridesmaids", "genre": "Comedy", "rating": 6.8},
    {"title": "Pineapple Express", "genre": "Comedy", "rating": 6.9},
    {"title": "The Dictator", "genre": "Comedy", "rating": 6.4},
    {"title": "Borat", "genre": "Comedy", "rating": 7.3},
    {"title": "Borat Subsequent Moviefilm", "genre": "Comedy", "rating": 6.6},
    {"title": "Monty Python and the Holy Grail", "genre": "Comedy", "rating": 8.2},
    {"title": "The Big Lebowski", "genre": "Comedy", "rating": 8.1},
    {"title": "Napoleon Dynamite", "genre": "Comedy", "rating": 7.0},
    {"title": "Mean Girls", "genre": "Comedy", "rating": 7.1},
    {"title": "Legally Blonde", "genre": "Comedy", "rating": 6.4},
    {"title": "Freaky Friday", "genre": "Comedy", "rating": 6.3},
    {"title": "The 40-Year-Old Virgin", "genre": "Comedy", "rating": 7.1},
    {"title": "Dodgeball: A True Underdog Story", "genre": "Comedy", "rating": 6.7},
    {"title": "Talladega Nights: The Ballad of Ricky Bobby", "genre": "Comedy", "rating": 6.6},
    {"title": "Yes Man", "genre": "Comedy", "rating": 6.8},
    {"title": "Liar Liar", "genre": "Comedy", "rating": 6.9},
    {"title": "Ace Ventura: Pet Detective", "genre": "Comedy", "rating": 6.9},
    {"title": "Bruce Almighty", "genre": "Comedy", "rating": 6.7},
    {"title": "Click", "genre": "Comedy", "rating": 6.4},
    {"title": "Billy Madison", "genre": "Comedy", "rating": 6.3},
    {"title": "Happy Gilmore", "genre": "Comedy", "rating": 7.0},
    {"title": "The Mask", "genre": "Comedy", "rating": 6.9},
    {"title": "Super Troopers", "genre": "Comedy", "rating": 7.1},
    {"title": "EuroTrip", "genre": "Comedy", "rating": 6.6},
    {"title": "Paul", "genre": "Comedy", "rating": 7.0},
    {"title": "Ted", "genre": "Comedy", "rating": 6.9},
    {"title": "Ted 2", "genre": "Comedy", "rating": 6.3},
    {"title": "The Conjuring", "genre": "Horror", "rating": 7.5},
    {"title": "A Quiet Place", "genre": "Horror", "rating": 7.6},
    {"title": "Hereditary", "genre": "Horror", "rating": 7.4},
    {"title": "The Exorcist", "genre": "Horror", "rating": 8.0},
    {"title": "Get Out", "genre": "Horror", "rating": 7.7},
    {"title": "The Babadook", "genre": "Horror", "rating": 6.8},
    {"title": "Halloween", "genre": "Horror", "rating": 7.8},
    {"title": "The Shining", "genre": "Horror", "rating": 8.4},
    {"title": "It", "genre": "Horror", "rating": 7.3},
    {"title": "Saw", "genre": "Horror", "rating": 7.6},
    {"title": "Scream", "genre": "Horror", "rating": 7.3},
    {"title": "Paranormal Activity", "genre": "Horror", "rating": 6.3},
    {"title": "The Ring", "genre": "Horror", "rating": 7.1},
    {"title": "The Grudge", "genre": "Horror", "rating": 5.9},
    {"title": "The Others", "genre": "Horror", "rating": 7.6},
    {"title": "The Blair Witch Project", "genre": "Horror", "rating": 6.5},
    {"title": "Sinister", "genre": "Horror", "rating": 6.8},
    {"title": "Insidious", "genre": "Horror", "rating": 6.8},
    {"title": "The Autopsy of Jane Doe", "genre": "Horror", "rating": 6.8},
    {"title": "Don't Breathe", "genre": "Horror", "rating": 7.1},
    {"title": "The Evil Dead", "genre": "Horror", "rating": 7.4},
    {"title": "Evil Dead II", "genre": "Horror", "rating": 7.7},
    {"title": "Army of Darkness", "genre": "Horror", "rating": 7.4},
    {"title": "Candyman", "genre": "Horror", "rating": 6.7},
    {"title": "The Mist", "genre": "Horror", "rating": 7.1},
    {"title": "The Descent", "genre": "Horror", "rating": 7.2},
    {"title": "The Cabin in the Woods", "genre": "Horror", "rating": 7.0},
    {"title": "It Follows", "genre": "Horror", "rating": 6.8},
    {"title": "Us", "genre": "Horror", "rating": 6.8},
    {"title": "The Witch", "genre": "Horror", "rating": 6.9},
    {"title": "Doctor Sleep", "genre": "Horror", "rating": 7.3},
    {"title": "The Texas Chainsaw Massacre", "genre": "Horror", "rating": 7.5},
    {"title": "Drag Me to Hell", "genre": "Horror", "rating": 6.5},
    {"title": "The Invitation", "genre": "Horror", "rating": 6.6},
    {"title": "1408", "genre": "Horror", "rating": 6.8},
    {"title": "The Boy", "genre": "Horror", "rating": 6.0},
    {"title": "The Nun", "genre": "Horror", "rating": 5.3},
    {"title": "Annabelle", "genre": "Horror", "rating": 5.4},
    {"title": "Annabelle: Creation", "genre": "Horror", "rating": 6.5},
    {"title": "Smile", "genre": "Horror", "rating": 6.7},
    {"title": "Midsommar", "genre": "Horror", "rating": 7.1},
    {"title": "Scary Stories to Tell in the Dark", "genre": "Horror", "rating": 6.2},
    {"title": "The Silence", "genre": "Horror", "rating": 5.3},
    {"title": "The Conjuring 2", "genre": "Horror", "rating": 7.3},
    {"title": "Lights Out", "genre": "Horror", "rating": 6.3},
    {"title": "The Orphanage", "genre": "Horror", "rating": 7.4},
    {"title": "The Devil's Backbone", "genre": "Horror", "rating": 7.4},
    {"title": "The House of the Devil", "genre": "Horror", "rating": 6.4},
    ]

    return jsonify({"user_id": user_id, "recommendations": recommended_movies})

if __name__ == "__main__":
    app.run(debug=True, port=5000)  # Change port
